In [30]:
import pandas as pd 
import numpy as np

In [31]:
df = pd.read_csv(r"C:\Users\hp\Downloads\Sample - Superstore.csv", encoding='latin1')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [32]:
df.columns = df.columns.str.replace(' ', '_').str.replace('-', '_')

In [33]:
print("Shape:", df.shape)
print("\nDtypes:\n", df.dtypes)
print("\nNull values:\n", df.isnull().sum())
print("\nDuplicates:", df.duplicated().sum())
print("\nSample:\n", df.head(3))

Shape: (9994, 21)

Dtypes:
 Row_ID             int64
Order_ID          object
Order_Date        object
Ship_Date         object
Ship_Mode         object
Customer_ID       object
Customer_Name     object
Segment           object
Country           object
City              object
State             object
Postal_Code        int64
Region            object
Product_ID        object
Category          object
Sub_Category      object
Product_Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

Null values:
 Row_ID           0
Order_ID         0
Order_Date       0
Ship_Date        0
Ship_Mode        0
Customer_ID      0
Customer_Name    0
Segment          0
Country          0
City             0
State            0
Postal_Code      0
Region           0
Product_ID       0
Category         0
Sub_Category     0
Product_Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

Duplicates: 0

Sample:
    Row_ID        Order_ID Order_Date   Ship_Date     Ship_Mode Customer_ID  \
0       1  CA-2016-152156  11/8/2016  11/11/2016  Second Class    CG-12520
1       2  CA-2016-152156  11/8/2016  11/11/2016  Second Class    CG-12520
2       3  CA-2016-138688  6/12/2016   6/16/2016  Second Class    DV-13045

     Customer_Name    Segment        Country         City  ... Postal_Code  \
0      Claire Gute   Consumer  United States    Henderson  ...       42420
1      Claire Gute   Consumer  United States    Henderson  ...       42420
2  Darrin Van Huff  Corporate  United States  Los Angeles  ...       90036

   Region       Product_ID         Category Sub_Category  \
0   South  FUR-BO-10001798        Furniture    Bookcases
1   South  FUR-CH-10000454        Furniture       Chairs
2    West  OFF-LA-10000240  Office Supplies       Labels

                                        Product_Name   Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.96         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.94         3
2  Self-Adhesive Address Labels for Typewriters b...   14.62         2

   Discount    Profit
0       0.0   41.9136
1       0.0  219.5820
2       0.0    6.8714

[3 rows x 21 columns]

In [34]:
# ── 3. FIX DATA TYPES ────────────────────────────────────────────────────────
df['Order_Date']  = pd.to_datetime(df['Order_Date'], format='mixed')
df['Ship_Date']   = pd.to_datetime(df['Ship_Date'],  format='mixed')
df['Postal_Code'] = df['Postal_Code'].astype(str).str.strip()

In [35]:
#Remove duplicate rows
df[df.duplicated(subset = ['Order_ID', 'Product_ID'])]

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit
352,353,CA-2016-129714,2016-09-01,2016-09-03,First Class,AB-10060,Adam Bellavance,Home Office,United States,New York City,...,10009,East,OFF-PA-10001970,Office Supplies,Paper,Xerox 1881,49.120,4,0.0,23.0864
431,432,US-2016-123750,2016-04-15,2016-04-21,Standard Class,RB-19795,Ross Baird,Home Office,United States,Gastonia,...,28052,South,TEC-AC-10004659,Technology,Accessories,Imation Secure+ Hardware Encrypted USB 2.0 Fla...,291.960,5,0.2,54.7425
1301,1302,CA-2016-137043,2016-12-23,2016-12-25,Second Class,LC-17140,Logan Currie,Consumer,United States,Springfield,...,22153,South,FUR-FU-10003664,Furniture,Furnishings,"Electrix Architect's Clamp-On Swing Arm Lamp, ...",286.380,3,0.0,83.0502
3184,3185,CA-2017-152912,2017-11-09,2017-11-12,Second Class,BM-11650,Brian Moss,Corporate,United States,Columbia,...,21044,East,OFF-ST-10003208,Office Supplies,Storage,Adjustable Depth Letter/Legal Cart,544.380,3,0.0,157.8702
3406,3407,US-2014-150119,2014-04-23,2014-04-27,Standard Class,LB-16795,Laurel Beltran,Home Office,United States,Columbus,...,43229,East,FUR-CH-10002965,Furniture,Chairs,Global Leather Highback Executive Chair with P...,281.372,2,0.3,-12.0588
6500,6501,CA-2015-103135,2015-07-24,2015-07-28,Standard Class,SS-20515,Shirley Schmidt,Home Office,United States,Louisville,...,40214,South,OFF-BI-10000069,Office Supplies,Binders,"GBC Prepunched Paper, 19-Hole, for Binding Sys...",90.060,6,0.0,41.4276
7882,7883,CA-2017-118017,2017-12-03,2017-12-06,Second Class,LC-16870,Lena Cacioppo,Consumer,United States,Thornton,...,80229,West,TEC-AC-10002006,Technology,Accessories,Memorex Micro Travel Drive 16 GB,102.336,8,0.2,14.0712
9169,9170,CA-2016-140571,2016-03-15,2016-03-19,Standard Class,SJ-20125,Sanjit Jacobs,Home Office,United States,Jackson,...,39212,South,OFF-PA-10001954,Office Supplies,Paper,Xerox 1964,45.680,2,0.0,21.0128

In [36]:
df= df.drop_duplicates(subset=['Order_ID', 'Product_ID'])

In [37]:
# ── 4. PRE-CLEAN VALIDATION ──────────────────────────────────────────────────
print("\n--- Pre-Clean Validation ---")
print("Negative/Zero Sales:  ", (df['Sales'] <= 0).sum())
print("Invalid Discounts:    ", ((df['Discount'] < 0) | (df['Discount'] > 1)).sum())
print("Ship before Order:    ", (df['Ship_Date'] < df['Order_Date']).sum())

--- Pre-Clean Validation ---
Negative/Zero Sales:   0
Invalid Discounts:     0
Ship before Order:     0

In [38]:

# ── 5. CLEAN ─────────────────────────────────────────────────────────────────
# Standardize text columns
text_cols = ['Customer_Name', 'Segment', 'City', 'State', 'Region',
             'Category', 'Sub_Category', 'Product_Name', 'Ship_Mode']
for col in text_cols:
    df[col] = df[col].str.strip().str.title()

# Remove invalid discounts
df = df[(df['Discount'] >= 0) & (df['Discount'] <= 1)].reset_index(drop=True)

# Remove zero or negative sales
df = df[df['Sales'] > 0].reset_index(drop=True)

# Drop duplicates
df.drop_duplicates(inplace=True)

# Drop rows where critical fields are null
df.dropna(subset=['Order_ID', 'Customer_ID', 'Product_ID', 'Sales'], inplace=True)

# Reset index
df.reset_index(drop=True, inplace=True)

print("\n--- After Cleaning ---")
print("Shape:", df.shape)
print("Nulls:\n", df.isnull().sum())

--- After Cleaning ---
Shape: (9986, 21)
Nulls:
 Row_ID           0
Order_ID         0
Order_Date       0
Ship_Date        0
Ship_Mode        0
Customer_ID      0
Customer_Name    0
Segment          0
Country          0
City             0
State            0
Postal_Code      0
Region           0
Product_ID       0
Category         0
Sub_Category     0
Product_Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

C:\Users\hp\AppData\Local\Temp\ipykernel_22204\2832940042.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.strip().str.title()

In [39]:
# ── 6. DERIVED COLUMNS ───────────────────────────────────────────────────────
# 1. Profit Margin %
df['Profit_Margin_Pct'] = np.where(
    df['Sales'] > 0,
    (df['Profit'] / df['Sales'] * 100).round(2),
    0
)

# 2. Delivery Days
df['Delivery_Days'] = (df['Ship_Date'] - df['Order_Date']).dt.days

# 3. Discount Band
df['Discount_Band'] = pd.cut(
    df['Discount'],
    bins=[-0.001, 0.001, 0.2, 0.4, 1.0],
    labels=['No Discount', 'Low (1-20%)', 'Medium (21-40%)', 'High (41%+)']
)
df['Discount_Band'] = df['Discount_Band'].astype(str)

# 4. Order Year and Month
df['Order_Year']       = df['Order_Date'].dt.year
df['Order_Month']      = df['Order_Date'].dt.month
df['Order_Month_Name'] = df['Order_Date'].dt.strftime('%b')

# 5. Season
df['Season'] = df['Order_Month'].map({
    12: 'Winter', 1: 'Winter',  2: 'Winter',
    3:  'Spring', 4: 'Spring',  5: 'Spring',
    6:  'Summer', 7: 'Summer',  8: 'Summer',
    9:  'Fall',   10: 'Fall',   11: 'Fall'
})

# 6. Is Loss flag
df['Is_Loss'] = df['Profit'].apply(lambda x: 'Loss' if x < 0 else 'Profit')

# 7. Margin Band
def margin_band(m):
    if m >= 20:   return 'High (>=20%)'
    elif m >= 10: return 'Medium (10-20%)'
    elif m >= 0:  return 'Low (0-10%)'
    else:         return 'Loss'

df['Margin_Band'] = df['Profit_Margin_Pct'].apply(margin_band)

# 8. Sales Bucket
df['Sales_Bucket'] = pd.cut(
    df['Sales'],
    bins=[0, 50, 200, 500, 1000, 25000],
    labels=['Micro (<$50)', 'Small ($50-200)', 'Medium ($200-500)',
            'Large ($500-1K)', 'XL (>$1K)']
)
df['Sales_Bucket'] = df['Sales_Bucket'].astype(str)

# 9. Revenue per Unit
df['Revenue_per_Unit'] = (df['Sales'] / df['Quantity']).round(2)

# 10. Profit per Unit
df['Profit_per_Unit'] = (df['Profit'] / df['Quantity']).round(2)

# 11. Discount Amount
df['Discount_Amount'] = (df['Sales'] * df['Discount']).round(2)

# 12 Ship Speed 
df['Ship_Speed'] = df['Ship_Mode'].map({
    'Same Day': 'Express',
    'First Class': 'Fast',
    'Second Class': 'Standard',
    'Standard Class': 'Economy'
})

# Handle any unexpected values
df['Ship_Speed'] = df['Ship_Speed'].fillna('Economy')

print("\n--- Derived Columns Added ---")
print(df[['Sales', 'Profit', 'Profit_Margin_Pct', 'Delivery_Days',
          'Discount_Band', 'Order_Year', 'Order_Month', 'Order_Month_Name',
          'Season', 'Is_Loss', 'Margin_Band', 'Sales_Bucket',
          'Revenue_per_Unit', 'Profit_per_Unit', 'Discount_Amount','Ship_Speed']].head(5).to_string())

--- Derived Columns Added ---
      Sales    Profit  Profit_Margin_Pct  Delivery_Days Discount_Band  Order_Year  Order_Month Order_Month_Name  Season Is_Loss      Margin_Band       Sales_Bucket  Revenue_per_Unit  Profit_per_Unit  Discount_Amount Ship_Speed
0  261.9600   41.9136              16.00              3   No Discount        2016           11              Nov    Fall  Profit  Medium (10-20%)  Medium ($200-500)            130.98            20.96             0.00   Standard
1  731.9400  219.5820              30.00              3   No Discount        2016           11              Nov    Fall  Profit     High (>=20%)    Large ($500-1K)            243.98            73.19             0.00   Standard
2   14.6200    6.8714              47.00              4   No Discount        2016            6              Jun  Summer  Profit     High (>=20%)       Micro (<$50)              7.31             3.44             0.00   Standard
3  957.5775 -383.0310             -40.00              7   High (41%+)        2015           10              Oct    Fall    Loss             Loss    Large ($500-1K)            191.52           -76.61           430.91    Economy
4   22.3680    2.5164              11.25              7   Low (1-20%)        2015           10              Oct    Fall  Profit  Medium (10-20%)       Micro (<$50)             11.18             1.26             4.47    Economy

In [40]:
# ── 7. PRE-SPLIT VALIDATION ──────────────────────────────────────────────────
conflicts_city    = df.groupby('Customer_ID')['City'].nunique()
conflicts_segment = df.groupby('Customer_ID')['Segment'].nunique()
print("\nCustomers with multiple Cities:   ", (conflicts_city > 1).sum())
print("Customers with multiple Segments: ", (conflicts_segment > 1).sum())

Customers with multiple Cities:    780
Customers with multiple Segments:  0

In [41]:

# ── 8. SPLIT INTO 3 TABLES ───────────────────────────────────────────────────
# Fact Table
transaction_data = df[[
    'Order_ID', 'Order_Date', 'Ship_Date', 'Ship_Mode', 'Ship_Speed',
    'Customer_ID', 'Product_ID',
    'Sales', 'Quantity', 'Discount', 'Profit',
    'Profit_Margin_Pct', 'Delivery_Days', 'Discount_Band',
    'Order_Year', 'Order_Month', 'Order_Month_Name', 'Season', 'Is_Loss',
    'Margin_Band', 'Sales_Bucket', 'Revenue_per_Unit',
    'Profit_per_Unit', 'Discount_Amount'
]].copy()
print(df[['Ship_Mode', 'Ship_Speed']].drop_duplicates().to_string())

# Dimension — customer
customer_data = df[[
    'Customer_ID', 'Customer_Name', 'Segment',
    'City', 'State', 'Postal_Code', 'Region'
]].drop_duplicates(subset='Customer_ID').reset_index(drop=True)

# Dimension — product
product_data = df[[
    'Product_ID', 'Category', 'Sub_Category', 'Product_Name'
]].drop_duplicates(subset='Product_ID').reset_index(drop=True)

          Ship_Mode Ship_Speed
0      Second Class   Standard
3    Standard Class    Economy
35      First Class       Fast
365        Same Day    Express

In [42]:

# ── 9. POST-SPLIT VALIDATION ─────────────────────────────────────────────────
print("\n--- Table Shapes ---")
print("transaction_data:", transaction_data.shape)
print("customer_data:   ", customer_data.shape)
print("product_data:    ", product_data.shape)

unmatched_cust = transaction_data[~transaction_data['Customer_ID'].isin(customer_data['Customer_ID'])]
unmatched_prod = transaction_data[~transaction_data['Product_ID'].isin(product_data['Product_ID'])]
print("\nUnmatched Customer_IDs:", len(unmatched_cust))
print("Unmatched Product_IDs: ", len(unmatched_prod))

print("\nDelivery Days — negative values:", (transaction_data['Delivery_Days'] < 0).sum())
print("Discount_Band — 'nan' values:   ", (transaction_data['Discount_Band'] == 'nan').sum())
print("Sales_Bucket  — 'nan' values:   ", (transaction_data['Sales_Bucket']  == 'nan').sum())

--- Table Shapes ---
transaction_data: (9986, 24)
customer_data:    (793, 7)
product_data:     (1862, 4)

Unmatched Customer_IDs: 0
Unmatched Product_IDs:  0

Delivery Days — negative values: 0
Discount_Band — 'nan' values:    0
Sales_Bucket  — 'nan' values:    0

In [43]:
# ── 10. EXPORT ───────────────────────────────────────────────────────────────
output_path = r"C:\Users\hp\Desktop\project\\"

transaction_data.to_csv(output_path + "transaction_data.csv", index=False)
customer_data.to_csv(output_path    + "customer_data.csv",    index=False)
product_data.to_csv(output_path     + "product_data.csv",     index=False)
df.to_csv(output_path               + "superstore_clean.csv", index=False)

print("\n✅ All files exported successfully.")
print(f"   transaction_data.csv  → SQL project")
print(f"   customer_data.csv     → SQL project")
print(f"   product_data.csv      → SQL project")
print(f"   superstore_clean.csv  → Power BI dashboard")

✅ All files exported successfully.
   transaction_data.csv  → SQL project
   customer_data.csv     → SQL project
   product_data.csv      → SQL project
   superstore_clean.csv  → Power BI dashboard